### PR TITLE
Added customisability for arrow width (arrowWidth prop)

### PR DESCRIPTION
**Pull request by dj-neza**
Hi!
I recently opened an issue regarding arrow width not being customisable and the width: inherit acting weirdly with custom settings of imageWidth and width props. I took the liberty of adding towards your library. 

Regards,
Neza

### CODE REVIEW

**Comment by quanlieu** [comment]
Hi Neza,

First, I appreciate your support toward my library which I made out of free time.
I really want to help you but I lost my access credential to npm a long time ago, I'm afraid there is no point in merge this PR.
I think you can just create your own npm package or just copy it this into your work. You can do whatever you want with this source code, I am O.K. with it.

**Comment by dj-neza** [comment]
Okay deal I'll try to create a npm package. You might want to update the readme to tell people it won't be maintained and updated anymore. If you want I can take over the maintenance through a new npm package :)

**Comment by quanlieu** [comment]
Hi dj-neza, it is up to you, actually. If you'd like to maintenance it, I'll add a link to your new package.

**Comment by dj-neza** [comment]
Sure then I'll open up a new repo and let you know once it's published! :)

**Pull request merged**
